### PR TITLE
Configure pytest runner for vscode

### PR DESCRIPTION
**Pull request by bwalderman**
Add pytest configs for the Python vscode extension. Makes it possible to discover, run, and debug tests through the GUI.

### CODE REVIEW

**Review by sadym-chromium — APPROVED** [review]

**Comment by sadym-chromium** [comment]
I rolled back the PR and added instructions to readme in order to keep the project IDE-agnostic: https://github.com/sadym-chromium/bidiInChromeContext/commit/25c518ce720f041fb9b656e55425a0ce35777641

**Comment by foolip** [comment]
FWIW, https://github.com/mdn/browser-compat-data is a repo I work in a lot, and it has a [.vscode directory](https://github.com/mdn/browser-compat-data/tree/main/.vscode). I find that pretty convenient because I do use VS Code.

To the extent that editor-agnostic alternatives exist, where https://editorconfig.org/ is an example of that, I think we should use those. But I think we should accept PRs for extra settings for any editor that any contributor uses, it's not an inconvenience for anyone, but is helpful for some.

**Comment by mathiasbynens** [comment]
I agree. The project remains IDE-agnostic since none of the functionality depends on these editor-specific configurations. I see it as an example of progressive enhancement :)

**Comment by mathiasbynens** [comment]
PR: https://github.com/sadym-chromium/bidiInChromeContext/pull/17

**Pull request merged**
